---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "(Archived) Second University Village Home Owners Association"
keywords:    "SUVHOA, Second University, Home Owners Association, HOA"
description: "(Archived) Second University Village Home Owners Association"
source_link: "https://sysadmininator.com/suvhoa"
favicon:     "img/icons8-home-512.png"
touch_icon:  "img/icons8-home-512.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  purple:    '#c869bf'
  turquoise: '#0fbfcf'
  olive:     '#bea925'
  red:       '#ff0000'
  orange:    '#fab125'
  orange2:   '#ff7f00'
  yellow:    '#ffff00'
  green:     '#9bcf2f'
  green2:    '#00ff00'
  blue:      '#49a7e9'
  blue2:     '#0000ff'
  indigo:    '#4b0082'
  violet:    '#9400d3'
  softrn1:   '#FF9AA2'
  softrn2:   '#FFB7B2'
  softrn3:   '#FFDAC1'
  softrn4:   '#E2F0CB'
  softrn5:   '#B5EAD7'
  softrn6:   '#C7CEEA'
  pastrn1:   '#FF6663'
  pastrn2:   '#FEB144'
  pastrn3:   '#FDFD97'
  pastrn4:   '#9EE09E'
  pastrn5:   '#9EC1CF'
  pastrn6:   '#CC99C9'

kramdown:
  auto_ids:  false

